appname  : ContactMyReps
layout   : main
charset  : UTF-8
template : template_toolkit

route_modules :
    FindByAddress : 1
    Email         : 1

logger : LogAny

engines :
    template :
        template_toolkit :
            start_tag : '[%'
            end_tag   : '%]'
    logger :
         LogAny :
             category : ContactMyReps
